//! Agent-facing CLI contracts for [`clap`] applications.
//!
//! `clap_schema` joins four sources of truth:
//!
//! - [`clap::Command`] owns invocation syntax and command structure.
//! - `#[clap_schema::handler]` marks the implementation for each leaf payload.
//! - Rust owns each handler's successful `Result<Output, _>` type.
//! - [`schemars::JsonSchema`] owns semantic input and output shapes.
//!
//! Runtime dispatch remains ordinary Rust. The handler attribute only emits
//! compile-time contract glue keyed by a free function's first argument type or
//! an inherent method's owned `self` type. Handlers are never executed while the
//! contract is built.
//!
//! # Derive and handler API
//!
//! ```
//! use clap::{Args, Parser, Subcommand};
//! use clap_schema::{CliSchema, CommandSchema, JsonSchema};
//!
//! #[derive(Debug, Parser, CliSchema)]
//! struct Cli {
//!     #[command(subcommand)]
//!     command: Commands,
//!
//!     /// Emit machine-readable output.
//!     #[arg(long, global = true)]
//!     json: bool,
//! }
//!
//! #[derive(Debug, Subcommand, CommandSchema)]
//! enum Commands {
//!     /// Create an item.
//!     Create(CreateArgs),
//! }
//!
//! #[derive(Debug, Args, JsonSchema)]
//! struct CreateArgs {
//!     #[arg(long)]
//!     name: String,
//! }
//!
//! #[derive(Debug, JsonSchema)]
//! struct Item {
//!     id: u64,
//!     name: String,
//! }
//!
//! #[clap_schema::handler]
//! async fn create(_command: CreateArgs) -> Result<Item, std::io::Error> {
//!     Ok(Item { id: 1, name: "example".to_owned() })
//! }
//!
//! let contract = Cli::schema()?;
//! let create = contract.command(&["create"]).expect("create command");
//! assert!(create.output.is_some());
//! # Ok::<(), clap_schema::Error>(())
//! ```
//!
//! Handlers may be synchronous or asynchronous, and may be free functions or
//! inherent methods with an owned `self` receiver. A handler returning
//! `Result<(), E>` naturally produces no successful output schema. Error types
//! are intentionally outside the schema contract. A contract-visible leaf must
//! use a local one-field tuple payload whose canonical handler is marked with
//! `#[clap_schema::handler]`.

#[expect(
    unused_extern_crates,
    reason = "proc-macro expansions refer to this crate through `::clap_schema`"
)]
extern crate self as clap_schema;

mod builder;
mod error;
mod model;
mod reflect;
mod schema;
mod semantic;
mod spec;

#[doc(hidden)]
pub mod __private;

pub use builder::ContractBuilder;
#[cfg(feature = "derive")]
pub use clap_schema_derive::{CliSchema, CommandSchema, handler};
pub use error::{Error, Result};
pub use model::{
    ArgumentInvocation, CONTRACT_VERSION, CatalogEntry, CliContract, CommandContract,
    ContextArgument, InputConstraint, InputContract, InputTransport, JSON_SCHEMA_DIALECT,
    OutputContract, OutputFormat, OutputSelector, ProgramContract, PropertyBinding,
    StructuredFormat, ValueEncoding, ValueShape,
};
pub use schemars::{JsonSchema, Schema};
pub use spec::{CommandSpec, JsonOutput, StructuredInput};

/// Trait implemented by an agent-contract-aware root clap parser.
///
/// Prefer `#[derive(CliSchema)]` when the `derive` feature is enabled.
pub trait CliSchema: clap::CommandFactory {
    /// Subcommand enum that owns the executable command contracts.
    type Commands: CommandSchema;

    /// Returns root-level contract configuration generated by the derive.
    #[doc(hidden)]
    fn __clap_schema_root() -> __private::RootSpec {
        __private::RootSpec::default()
    }

    /// Builds the validated agent-facing contract for this CLI.
    ///
    /// # Errors
    ///
    /// Returns an error when typed schema declarations and clap invocation
    /// syntax cannot be joined into a complete contract.
    fn schema() -> Result<CliContract>
    where
        Self: Sized,
    {
        __private::build_derived::<Self>()
    }
}

/// Trait implemented by subcommand enums that contribute typed command schemas.
///
/// Prefer `#[derive(CommandSchema)]` when the `derive` feature is enabled.
pub trait CommandSchema: clap::Subcommand {
    /// Registers executable leaf contracts below `prefix`.
    #[doc(hidden)]
    fn __clap_schema_register(
        prefix: &mut Vec<String>,
        registry: &mut __private::Registry,
    ) -> Result<()>;
}
